#!/bin/sh

#######################################
# Filter strange auth on an instance
# from /var/log/auth.log

if [ -z "$1" ]; then
  echo "usage: cheat <cli tool name>"
fi

cheat() {
  where="$1"
  if [ $# -ge 1 ]; then
    shift
  fi
  IFS=+ curl "http://cht.sh/$where/ $*"
}

cheat $*
