#!/bin/bash

thisfile="README.md"

echo "creating: $thisfile"
touch "$thisfile"

cat > $thisfile << 'EOM'
[![name](url_img)]

[action_name]: https://github.com/user/project/workflows/dir/badge.svg?branch=master
[li-badge]: https://img.shields.io/github/license/user/project
[li-style]: [(https://img.shields.io/badge/code_style-prettier-ff69b4.svg?style=flat-square)](https://github.com/prettier/prettier)


# TITLE ![GitHub][li-badge] ![tile_jobs][action_name] [![code_style: prettier][li-style]]

> description

## Highlights

- features

## Prerequisite

Work best or must have:

- this

## Install

```sh
```

## Usage

> how?

## Maintainers

- [user][me]

[me]: https://github.com/user
[me]: https://gitlab.com/user
EOM

