#!/bin/bash

if [ -z "$1" ]; then
  echo "usage: roll <?number><dice type>"
fi

declare -A dicetype
declare -A diceicon

dicetype[d4]="tetrahedron"
dicetype[d6]="cube"
dicetype[d8]="octahedron"
dicetype[d10]="pentagonal trapezohedron"
dicetype[d12]="dodecahedron"
dicetype[d20]="icosahedron"
diceicon[d4]="﫪"
diceicon[d6]="﫫"
diceicon[d8]="﫬"
diceicon[d10]="ﱭ"
diceicon[d12]="ﱬ"
diceicon[d20]="﫩"


rolldie() {
   local result=$1 sides=$2
   rolled=$(( ( RANDOM % sides ) + 1 ))
   eval "$result"=$rolled
}


for request in "$@"; do
  dice=$(echo "$request" | cut -dd -f1)
  sides=$(echo "$request" | cut -dd -f2)
  droll="d$sides"
  
  echo ""
  echo Rolling "$dice" "$droll" ${dicetype[$droll]}
  
  sum=0
  die=0
  
  while [[ ${dice:=1} -gt 0 ]]; do
    rolldie die "$sides"
	if [[ $droll == "d20" && $die == "20" ]]; then
	  echo "     ${diceicon[$droll]} dice roll = NATURAL $die"
    dragonrider
	else
	  echo "     ${diceicon[$droll]} dice roll = $die"
	fi
    sum=$(( sum + die ))
    dice=$(( dice - 1 ))
  done
  echo sum total = $sum
  echo ""
done

