#!/bin/sh

sudo apt update
sudo apt upgrade -y
sudo apt install tmux \
    ninja-build \
    gettext \
    libtool \
    libtool-bin \
    autoconf \
    automake \
    cmake \
    g++ \
    build-essential \
    pkg-config \
    unzip \
    vim \
    net-tools \
    alacitty \
    lynx \
    nnn \
    git \
    curl \
    jq \
    yq \
    nmap \
    tree \
    less \
    htop \
    vlc \
    xsel \
    fzf \
    fd-find \
    ripgrep \
    silversearcher-ag \
    lm-sensors \
    osm2pgsql \
    miller \
    neofetch \
    openssl \
    openvpn \
    gnome-tweak-tool \
    ansible
