#!/bin/sh

if ! which npm; then
  echo "Doesn't look like Node/NPM are installed."
  echo "Be sure to install them safely with install-node."
  exit 1
fi
# json2graphql emoji-finder emoj diagnostic-languageserver eslint_d ethers-cli prettier typescript-language-server
npm install -g yarn vercel serverless typescript @graphprotocol/graph-cli codesandbox
