#!/bin/sh

echo "which java"
echo "check: sudo apt install openjdk-14-jdk"
echo "java -version"

zip="LanguageTool-latest-snapshot.zip"
temp="/tmp/$zip"
dest="$HOME/.local/bin/languagetool"
curl -L https://internal1.languagetool.org/snapshots/$zip -o "$temp"

unzip -o -q "$temp" -d "$dest"

echo "LanguageTool installed"
