#!/usr/bin/env bash

# Install command-line tools using Homebrew.

# Make sure we’re using the latest Homebrew.
brew update

# Upgrade any already-installed formulae.
brew upgrade

# Save Homebrew’s installed location.
BREW_PREFIX=$(brew --prefix)

# Install GNU core utilities (those that come with macOS are outdated).
# Don’t forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
brew install coreutils
ln -s "${BREW_PREFIX}/bin/gsha256sum" "${BREW_PREFIX}/bin/sha256sum"


# Install GNU `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed.
brew install findutils
# Install GNU `sed`, overwriting the built-in `sed`.
brew install gnu-sed --with-default-names
# Install a modern version of Bash.
brew install bash
brew install bash-completion@2

# Switch to using brew-installed bash as default shell
if ! fgrep -q "${BREW_PREFIX}/bin/bash" /etc/shells; then
  echo "${BREW_PREFIX}/bin/bash" | sudo tee -a /etc/shells;
  chsh -s "${BREW_PREFIX}/bin/bash";
fi;

exec brew install gls ffmpeg youtube-dl binutils diffutils ed gawk gnu-indent lazygit weechat libtool gnu-tar gnu-which gnutls grep gzip tmux watch wdiff curl wget ctop reattach-to-user-namespace gdb gpatch m4 make file-formula git less openssh cointop unzip vim gpg gnupg jq bash lynx golang gpg gh pandoc nmap ansible ripgrep lsd neovim tree-sitter solidity ethereum nnn entr lazydocker

# Remove outdated versions from the cellar.
brew cleanup
echo "Now don't forget:"
echo "  Add /usr/local/bin/bash to /etc/shells"
echo "  Run chsh -s /usr/local/bin/bash"
echo "  Use #!/usr/bin/env bash as shebang line"