#!/bin/sh

exec brew install coreutils binutils diffutils ed findutils gawk gnu-indent gnu-sed gnu-tar gnu-which gnutls grep gzip tmux watch wdiff curl wget bash bash-completion gdb gpatch m4 make file-formula git less openssh unzip vim gpg jq bash lynx golang gpg gh pandoc nmap ansible

echo "Now don't forget:"
echo "  Add /usr/local/bin/bash to /etc/shells"
echo "  Run chsh -s /usr/local/bin/bash"
echo "  Use #!/usr/bin/env bash as shebang line"