#!/bin/sh

codename='lsb_release -cs'
echo 'deb http://download.opensuse.org/repositories/home:/ungoogled_chromium/Ubuntu_${codename^}/ /' | sudo tee /etc/apt/sources.list.d/home:ungoogled_chromium.list
curl -fsSL https://download.opensuse.org/repositories/home:ungoogled_chromium/Ubuntu_${codename^}/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home:ungoogled_chromium.gpg > /dev/null
sudo apt update
sudo apt install ungoogled-chromium
