#!/bin/sh
#webtorrent-desktop_0.23.0_amd64.deb

loc=$(curl -o /dev/null -sIw "%{redirect_url}" 'https://github.com/webtorrent/webtorrent-desktop/releases/latest')
vers=${loc##*/}
deb=webtorrent-desktop_$vers_amd64.deb

uri=${loc%/tag*}/download/$vers/$deb
echo "Downloading $uri"
curl -sL "$uri" -o "/tmp/$deb"

echo "Installing /tmp/$deb"
sudo dpkg -i "/tmp/$deb"
