#!/bin/sh

loc=$(curl -o /dev/null -sIw "%{redirect_url}" 'https://github.com/vercel/hyper/releases/latest')
vers=${loc##*/}
deb=hyper_$vers_amd64.deb

uri=${loc%/tag*}/download/$vers/$deb
echo "Downloading $uri"
curl -sL "$uri" -o "/tmp/$deb"

echo "Installing /tmp/$deb"
sudo dpkg -i "/tmp/$deb"
