#!/bin/sh

echo 'deb [arch=amd64] https://brave-browser-apt-beta.s3.brave.com/ stable main' | 
sudo tee /etc/apt/sources.list.d/brave-browser-beta.list
curl -s https://brave-browser-apt-beta.s3.brave.com/brave-core-nightly.asc | sudo apt-key --keyring /etc/apt/trusted.gpg.d/brave-browser-prerelease.gpg add -
sudo apt update
sudo apt install brave-browser-beta
