#!/bin/sh

if ! havecmd sysfsutils ; then
  telln '*Need to install `sysfsutils`*.'
  exit 1
fi

# allows you to tap the control stick which will simulate a left click
if [ "$1" = "1" ]; then
   echo "Turning on tap on TrackPoint"
   echo -n 1 > /sys/devices/platform/i8042/serio1/serio2/press_to_select
   exit 0
fi
if [ "$1" = "0" ]; then
   echo "Turning off tap on TrackPoint"
   echo -n 0 > /sys/devices/platform/i8042/serio1/serio2/press_to_select
   exit 0
fi
echo -n "Tap status: "

cat /sys/devices/platform/i8042/serio1/serio2/press_to_select


# Adjusting the speed and sensitivity of the TrackPoint
# edit the /etc/sysfs.conf. Add the following lines at the end.

#tweak trackpoint sysfs.conf
# devices/platform/i8042/serio1/serio2/sensitivity = 215
# devices/platform/i8042/serio1/serio2/rate = 280
# devices/platform/i8042/serio1/serio2/speed = 150
# devices/platform/i8042/serio1/serio2/inertia = 1

# Name	            Type	Default	Notes
# sensitivity	      Integer	128	Sensitivity
# speed	            Integer	97	Cursor speed
# inertia	          Integer	6	Described as "negative inertia." It acts more like friction. High values cause the cursor to snap backward when the Trackpoint is released
# reach	            Integer	10	Backup for Z-axis press
# draghys	          Integer	255	Drag hysteresis (how hard it is to drag with Z-axis pressed)
# mindrag	          Integer	20	Minimum amount of force needed to trigger dragging
# thresh	          Integer	8	Minimum value for a Z-axis press
# upthresh	        Integer	255	Used to generate a 'click' on Z-axis
# ztime	            Integer	38	How sharp of a press
# jenks	            Integer	135	Minimum curvature for double click
# press_to_select	  Boolean	0	Press to select
# skipback	        Boolean	0	Supress movement after drag release
# ext_dev	          Boolean	0	Disable external device

# sudo service sysfsutils restart
