#!/usr/bin/env bash

YYYY=$(date +%4Y)
COPYRIGHTS_DIR=`echo "${PWD%/*}" | perl -pe 's/^.*\/(\s)*//'`

if [ -f .gitignore ]; then
  for file in "$@"
  do
    TEMP_DIR=$(mktemp -d -t foobar.XXXXX)
    if [ "${file%/*}" != "$file" ]; then
      mkdir -p "$TEMP_DIR/${file%/*}"
    fi
    touch "$TEMP_DIR/$file"
    cat <(echo "// Copyright ${YYYY} ${COPYRIGHTS_DIR}
// SPDX-License-Identifier: Apache-2.0
") "$file" >> "$TEMP_DIR/$file"
    mv "$TEMP_DIR/$file" "$file"
  done
else
  echo "Error: you must be at the same level as the.gitignore file"
fi