#!/usr/bin/env bash

REPOSITORY="${PWD##*/}"
ROOTDIR=`echo "${PWD%/*}" | perl -pe 's/^.*\/(\s)*//'`

cargo init
echo "cargo new $REPOSITORY/$REPOSITORY"

newreadme > README.md
lcgnu2 > LICENCE
newgitignore > .gitignore
git init && git add .
echo "init cargo repo and basic files"
lsd -la
