#!/usr/bin/env bash

if [ -z "$1" ]; then
  echo "usage: discordtime <YYYY MM DD HH MM> (in GMT)" 
  exit
fi

epoch=$(date -d "$1-$2-$3 $4:$5:00 +0000" +"%s")
epoch_to_date=$(date -d @$epoch +%Y%m%d_%H%M%S)    

echo "date = $1/$2/$3 at $4:$5:00 GMT"
echo "epoch = $epoch"
echo "discord post = <t:$epoch:F>"