#!/bin/sh

# init  repo with basic files configurations

REPOSITORY="${PWD##*/}"
ROOTDIR=`echo "${PWD%/*}" | perl -pe 's/^.*\/(\s)*//'`

newreadme
echo "creating: README file"
lcgnu2 > LISENCE
echo "creating: LISENCE file"
newgitignore
echo "creating: gitignore file"
git init && git add .
echo "creating: git versioning"

# TODO if gitlab or if github
# command -v lsd >/dev/null && lsd -l || { ls -l; }
# echo "${grey}Push to create repo: ${greenyellow}git push --set-upstream git@gitlab.com:$ROOTDIR/$REPOSITORY.git master${reset}"
# echo "${grey}Add remote only: ${greenyellow}git remote add origin git@gitlab.com:$ROOTDIR/$REPOSITORY.git${reset}"
