#!/usr/bin/env bash

REPOSITORY="${PWD##*/}"
ROOTDIR=`echo "${PWD%/*}" | perl -pe 's/^.*\/(\s)*//'`

go mod init github.com/$ROOTDIR/$REPOSITORY
echo "go mod init github.com/$ROOTDIR/$REPOSITORY"

newreadme > README.md
lcapache > LICENSE
newgitignore > .gitignore
git init && git add .
echo "inititalized repository with git and basic files"
