#!/bin/bash

# Prints the current date as a path for use when creating content within
# a directory file structure that models chronological data. Accepts
# anything that can be passed to `date -d`.

TZ="GMT" date +"%Y%m%d%H%M%S" "$@"
