#!/bin/sh

# The world's best pastebin terminal replacement. 
# http://ix.io/
# cat file.ext | curl -F 'f:1=<-' ix.io
# curl -F 'f:1=@file.ext' ix.io

cat $1 | curl -F 'f:1=<-' ix.io

# if [ -n "$1" ]; then
#   exec curl -s "ix.io/$1"
# fi

# url=$(curl -s -F 'f:1=<-' http://ix.io)
# wee "$url" 2>/dev/null
# echo "$url"
# which xclip >/dev/null || exit 0
# echo "$url" | xclip 

