#!/bin/sh

if ! havecmd pup ; then
  telln '*Need to install `the Go lib pup`*.'
  exit 1
fi

WHEN=`curl -sL $1 | pup 'meta[property="article:published_time"] attr{content}'`
date -d $WHEN +"%A %d %B %Y @ %R"

