#!/bin/bash

dday=`isosec`
fn="$*"
cfn=${fn// /-}
thisfile="${dday}_${cfn}.md"

echo "creating: $thisfile"
touch "$thisfile"

cat > $thisfile << EOF
---
title: "$*"
author: $USER (github.com/$USER)
date: `date +"%FT%T%z"`
tags: []
template: {}
---

# $*

EOF
