#!/bin/bash

thisfile="README.md"
REPOSITORY="${PWD##*/}"
ROOTDIR=`echo "${PWD%/*}" | perl -pe 's/^.*\/(\s)*//'`

echo "creating: $thisfile"
touch "$thisfile"

cat > $thisfile << EOF
![WIP](https://img.shields.io/badge/status-wip-red)
![GitHub][li-badge] ![tile_jobs][action_name] [![code_style: prettier][li-style]]
[li-badge]: https://img.shields.io/github/license/$ROOTDIR/$REPOSITORY
[![Latest release](https://img.shields.io/github/v/release/$ROOTDIR/$REPOSITORY)](https://github.com/$ROOTDIR/$REPOSITORY/releases/latest)

# TITLE 

> description

## Prerequisite
Required:

- Node v14
- Yarn

## Install

```sh
```

## Usage

```sh
```

## Maintainers

- [$USER][me]

[me]: https://github.com/$USER

EOF
