#!/bin/bash

if ! havecmd jq ; then
  telln '*Need to install `jq`*.'
  exit 1
fi

if [ -z "$1" ]; then
  echo "usage: Open Ai GPT-3 ask something in one line"
  echo "make sure to source .env to load oai_api_key_1_/2/3"
fi

# source $hOME/.env or envx
API_ENDPOINT="https://api.openai.com/v1/completions"
MODEL=text-davinci-003
MAX_TOKEN=1500
TEMPERATURE=0
day_of_week=$(date +%u)

# If we are on sunday and tuesday
if [ $day_of_week == 0 ] || [ $day_of_week == 3 ]; then
  secret_key_=$oai_api_key_1_
# or on monday and friday 
elif [ $day_of_week == 1 ] || [ $day_of_week == 5 ]; then
  secret_key_=$oai_api_key_2_
else # so for wednesday, thursday, saturday
  secret_key_=$oai_api_key_3_
fi

RESPONSE=$(curl --silent -w "%{http_code}" -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $secret_key_" -d "{\"model\": \"$MODEL\", \"prompt\": \"$@\", \"max_tokens\": $MAX_TOKEN, \"temperature\": $TEMPERATURE}" $API_ENDPOINT)
HTTP_CODE="${RESPONSE: -3}"
RESPONSE="${RESPONSE:0:${#RESPONSE}-4}"
# RESPONSE="$(echo "$RESPONSE" | head -c -4)"
RESPONSE="$(echo $RESPONSE | jq -r '.choices[].text')"

gptChat() {
  if [ ${#RESPONSE} -gt 120 ]; then
    # actually lol maybe a bug there! but work as espected
    RESP=$(perl -pe 's/^"\\n//; s/\"$//; s/\\n//g' <<< "$RESPONSE")
    # RESP=$(perl -pe 's/^"\\n//; s/\"$//; s/\\"/"/g' <<< "$RESPONSE")
    echo -e "\n[\033[38;5;201mOPEN\033[0m\033[38;5;118mAI\033[0m] \t$RESP"
    echo "[$(TZ="GMT" date +"%Y%m%d%H%M%S") ME] $@" >> $SCRIPTS/openai.log 
    echo "[OPENAI] \t$RESP\n" >> $SCRIPTS/openai.log
  else
    RESP=$(perl -pe 's/^"\\n//; s/\"$//; s/\\n//g' <<< $RESPONSE)
    echo -e "\n[\033[38;5;201mOPEN\033[0m\033[38;5;118mAI\033[0m] $RESP"
    echo "[$(TZ="GMT" date +"%Y%m%d%H%M%S") ME] $@" >> $SCRIPTS/openai.log 
    echo "[OPENAI] $RESP\n" >> $SCRIPTS/openai.log
  fi
}

if [ "$HTTP_CODE" != "200" ]; then
    echo -e "\t🎰 oai_api_key_"$(( 1 + $RANDOM % 3 ))""
    sleep 3
    secret_key_=$oai_api_key_$(( 1 + $RANDOM % 3 ))
    gptChat
fi

if [ "$HTTP_CODE" == "200" ]; then
    gptChat
fi