#!/bin/sh
test -z "$1" && exit 1
YMLCONF="$DOTFILES/shared/alacritty/alacritty.yml"
perl -p -i -e 's/^*opacity:\s*\S+/opacity: '$1'/' $YMLCONF

# https://sw.kovidgoyal.net/kitty/remote-control/?highlight=dynamic_background_opacity#kitty-set-background-opacity
# kitty @ set-background-opacity $1
