#!/bin/bash

GHR_DIR="blackbook"
SESSION="NOTES"
NAME="notes"
TEMP_DIR=$(mktemp -d -t foobar.XXXXX)
NEW_NOTE="$(isosec)-new-note.md"

if tmux has-session -t $SESSION 2>/dev/null; then
  # If the session already exists, attach to it
  tmux -u attach-session -t $SESSION -d
else
    # Create a new session
    tmux -u new-window -n $NAME
    tmux -u new-session -s $SESSION -n $NAME -d

    # Split the window into panes
    tmux split-window -v -p 90

    # Set temp for dummy test
    tmux select-pane -t 0
    tmux send-keys "cd $TEMP_DIR" Enter
    tmux send-keys "c" Enter
    tmux send-keys "oai "

    # # Set the vim new notes
    tmux select-pane -t 1
    tmux send-keys "cd $GHREPOS/$GHR_DIR" Enter
    tmux send-keys "c" Enter
    tmux send-keys "vim $NEW_NOTE" Enter

    tmux -u attach-session -t $SESSION -d
fi