#!/usr/bin/env bash

if ! which docker 2>&1 >/dev/null; then
    echo "Please install 'docker' first"
    exit 1
fi

if [[ -n "$1" ]]; then
    docker run -it --network "$1" --rm ubuntu
else
    docker run -it --rm ubuntu
fi
