#!/bin/sh

if ! havecmd pup; then
  telln '*Need to install `the Go lib pup`*.'
  exit 1
fi

ETH=$(curl -sL etherscan.io | pup 'a[title="View Historical Ether Price"] text{}')
GAS=$(curl -sL etherscan.io | pup 'div[title="GasTracker Estimate for Average Gas"] text{}')
echo $ETH
echo $GAS
echo https://www.ethstats.net
