#!/usr/bin/env bash

cat <<'EOM'
![WIP](https://img.shields.io/badge/status-wip-red)

[![Latest release](https://img.shields.io/github/v/release/%ROOTDIR/%REPOSITORY)](https://github.com/%ROOTDIR/%REPOSITORY/releases/latest)
[![Go Reference](https://pkg.go.dev/badge/github.com/%ROOTDIR/%REPOSITORY.svg)](https://pkg.go.dev/github.com/%ROOTDIR/%REPOSITORY)
[![Go Report Card](https://goreportcard.com/badge/github.com/%ROOTDIR/%REPOSITORY)](https://goreportcard.com/report/github.com/%ROOTDIR/%REPOSITORY)
[![Coverage Status](https://coveralls.io/repos/github/%ROOTDIR/%REPOSITORY/badge.svg?branch=master)](https://coveralls.io/github/%ROOTDIR/%REPOSITORY?branch=master)
<a href="https://gitpod.io/#https://github.com/%ROOTDIR/%REPOSITORY" target="_blank">
  <img
    src="https://img.shields.io/badge/Open%20with-Gitpod-908a85?logo=gitpod"
    alt="Contribute with Gitpod"
  />
</a>

# %REPOSITORY

> description

## Install
### Prerequisite
> **Note**
>
>Required:
- [Foundry](https://book.getfoundry.sh/getting-started/installation)
- [Solidity](https://docs.soliditylang.org/)
- [Geth](https://geth.ethereum.org/docs/install-and-build/installing-geth)
- [Golang V1.19](https://go.dev/doc/install)
- [Docker](https://docs.docker.com/get-started/overview/)
- [Podman](https://podman-desktop.io/downloads)
- [Hasura CLI](https://hasura.io/docs/latest/graphql/core/hasura-cli/install-hasura-cli.html)
- [Next.js](https://nextjs.org/docs/basic-features)

```sh
git clone git@github.com:%ROOTDIR/%REPOSITORY.git
cd %REPOSITORY
go mod tidy         # to download modules
forge install       # to download the libs
```

## Usage
```sh
```
## Deployment
EOM
