#!/usr/bin/env bash

cat <<'EOM'
# %REPOSITORY

> description

## Install
### Prerequisite
- [Foundry](https://book.getfoundry.sh/getting-started/installation)
- [Solidity](https://docs.soliditylang.org/)
- [Geth](https://geth.ethereum.org/docs/install-and-build/installing-geth)
- [Golang V1.19](https://go.dev/doc/install)
- [Docker](https://docs.docker.com/get-started/overview/)
- [Podman](https://podman-desktop.io/downloads)
- [Next.js](https://nextjs.org/docs/basic-features)

```sh
git clone git@github.com:%ROOTDIR/%REPOSITORY.git
cd %REPOSITORY
go mod tidy 
forge install 
```

## Usage
```sh
```
EOM
