#!/bin/sh

#######################################
# "entity_id":"478651745610618"
# new RegExp(/entity_id":"(\d*)"/);
# vous etre pro
# programme de fiedilité

if [ -z "$1" ]; then
  echo "usage: fbid <cli tool name>"
fi

# fbid() {
#   `curl -sL 'https://www.facebook.com/$1' | perl -pe '/"entity_id":"\d"'`
# }

# fbid $*

# ytbID=`echo "$1" | sed -e "s|.*channel/||" -e "s|/.*$||"`
# ytbURL="https://www.youtube.com/channel/$ytbID"
# ytbNAME=`curl $ytbURL -so - | perl -l -0777 -ne 'print $1 if /<meta property="og:title" content="\s*(.*?)\s*"/si'`

# export MYCPUINFO1=`perl -lne 'print "$1" if /^model\sname\s:\s(.*$)/' /proc/cpuinfo | head -n 1`
# FBNAME=`echo "$1"`
FBURL="https://www.facebook.com/$1"

# ID=`curl -sL $FBURL | perl -pe  '/"entity_id":"(\d+)"/'`
ID=$(curl -sL $FBURL 2>&1 | grep entity_id)

echo "${ID}"
