#!/usr/bin/env bash

ARG_LN=${1:-1}
RWXROB_ZET="https://raw.githubusercontent.com/rwxrob/zet/main/docs/dex/changes.md"

curl --silent -L "$RWXROB_ZET" | head -n "$ARG_LN" | while read line; do
  # line_example="* 2022-12-29 09:37:19Z [Better to do type assertions in (central) `Pack` function](../1889)"
  line_pattern="^(.*\* [0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}Z \[.*\](.*))"
  if [[ ${line} =~ ${line_pattern} ]]; then
    FULL_ZET=$(perl -pe 's/\.\./https:\/\/rwxrob.github.io\/zet/g' <<<"$line")
    TIME=$(echo "$line" | perl -ne 'print "$1\n" if /([0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}Z)/')
    TEXT="$(echo "$line" | perl -ne 'print $1 if /\[([^\]]+)\]/')"
    LINK="$(echo "$FULL_ZET" | perl -ne 'print $1 if /\]\((.*?)\)/')"
  else
    echo "Error: Invalid string format"
    exit 1
  fi

  printf "[$TIME] \t$LINK \t$TEXT\n"
done
