#!/usr/bin/env bash

REPOSITORY="${PWD##*/}"
ROOTDIR=$(echo "${PWD%/*}" | perl -pe 's/^.*\/(\s)*//')

newreadme >README.md
lcapache >LICENSE
newgitignore >.gitignore
git init && git add .
echo "creating: git versioning"
