#!/bin/bash

if ! havecmd jq; then
  telln '*Need to install `jq`*.'
  exit 1
fi

if [ -z "$1" ]; then
  echo "usage: oai ask me something in one line"
  echo "make sure to *source .env* to load *gh_token_* and *gh_user_*"
fi

user_list=("$1" "$gh_user_")
TPMF=$(mktemp -d -t foobar.XXXXX)
for user in "${user_list[@]}"; do
  query='query {
      user(login: \"'$user'\") {
        starredRepositories(orderBy: {field: STARRED_AT, direction: DESC}) {
          nodes {
            nameWithOwner
            url
            stargazerCount
            description
            isTemplate
          }
        }
      }
    }'

  query="$(echo $query)"
  response=$(curl -s -H 'Content-Type: application/json' \
    -H "Authorization: bearer $gh_token_" \
    -X POST -d "{ \"query\": \"$query\"}" https://api.github.com/graphql)
  echo $response | jq '.data.user' >$TPMF/starred_repos_$user.json
done

touch "$TPMF/merged.json"
jq '.starredRepositories.nodes[]' "$TPMF/starred_repos_$1.json" "$TPMF/starred_repos_$gh_user_.json" >"$TPMF/merged.json"

echo "there are $(jq '.[]' "$TPMF/merged.json" | wc -l) repos starred"
echo "Enter to pretty print, 'l' to scroll with less, or enter your search term with ripgrep"

read -p "Enter your search or hit enter to scroll it: " user_search

if [[ -z "$user_search" ]]; then
  jq '.' "$TPMF/merged.json"
elif [[ "$user_search" == "l" ]]; then
  less $TPMF/merged.json
else
  rg $user_search $TPMF/merged.json
fi
