#!/bin/bash

if ! havecmd jq; then
  telln '*Need to install `jq`*.'
  exit 1
fi

if [ -z "$1" ]; then
  echo -e "Usage: make sure to load *gh_token_* and *gh_user_*. \nYou can add other github username if you like!\n\n"
  user_list=("$gh_user_" "$GITUSER")
else
  user_list=("$1" "$gh_user_" "$GITUSER")
fi

TPMF=$(mktemp -d -t foobar.XXXXX)
touch "$TPMF/merged.json"
for ghuser in "${user_list[@]}"; do
  query='query {
      user(login: \"'$ghuser'\") {
        starredRepositories(orderBy: {field: STARRED_AT, direction: DESC}) {
          nodes {
            nameWithOwner
            url
            stargazerCount
            description
            isTemplate
          }
        }
      }
    }'

  query="$(echo $query)"
  response=$(curl -s -H 'Content-Type: application/json' \
    -H "Authorization: bearer $gh_token_" \
    -X POST -d "{ \"query\": \"$query\"}" https://api.github.com/graphql)
  echo "$response" | jq '.data.user' >"$TPMF"/starred_repos_"$ghuser".json
  jq '.starredRepositories.nodes[]' "$TPMF/starred_repos_$ghuser.json" >>"$TPMF/merged.json"
done

echo "there are $(jq '.[]' "$TPMF/merged.json" | wc -l) repos starred"
echo "[ENTER] to print / [l] to scroll with less / [SEARCH TERM] to filter"

read -p "[OPTION]: " user_search

if [[ -z "$user_search" ]]; then
  jq '.' "$TPMF/merged.json"
elif [[ "$user_search" == "l" ]]; then
  less $TPMF/merged.json
else
  rg $user_search $TPMF/merged.json
fi
