#!/bin/sh

# Pulls down the external IP address used by this system or local area
# network in a safe, reliable way. Consider avoiding alternatives using
# curl that cannot be verified as legitimate organizations.
#
# Note this is a script instead of an exported function or alias so that
# it can be called by any executable in any language using some form of
# the exec() system call (man exec).

# hostname -I | cut -c-13
ipconfig getifaddr en0
dig +short myip.opendns.com @resolver4.opendns.com
#dig +short myip.opendns.com @resolver1.opendns.com -4
# dig -4 TXT +short o-o.myaddr.l.google.com @ns1.google.com
# dig -6 TXT +short o-o.myaddr.l.google.com @ns1.google.com
