#!/bin/sh
# test -z "$1" && exit 1
ARG=${1:-1}
YMLCONF="$DOTFILES/.config/alacritty/alacritty.toml"

# Update opacity
perl -p -i -e 's/^*opacity\s*=\s*\S+/opacity = '$ARG'/' $YMLCONF

# Set blur based on the value of ARG
if (( $(echo "$ARG == 0.1" | bc -l) )); then
    perl -p -i -e 's/^\s*blur\s*=\s*\S+/blur = false/' $YMLCONF
elif (( $(echo "$ARG > 0.8" | bc -l) )); then
    perl -p -i -e 's/^\s*blur\s*=\s*\S+/blur = false/' $YMLCONF
elif (( $(echo "$ARG > 0.1" | bc -l) && $(echo "$ARG <= 0.8" | bc -l) )); then
    perl -p -i -e 's/^\s*blur\s*=\s*\S+/blur = true/' $YMLCONF
fi

# Ensure the blur key is present in the file
if ! grep -q 'blur =' "$YMLCONF"; then
    if (( $(echo "$ARG > 0.1" | bc -l) && $(echo "$ARG <= 0.8" | bc -l) )); then
        echo 'blur = true' >> "$YMLCONF"
    else
        echo 'blur = false' >> "$YMLCONF"
    fi
fi

# https://sw.kovidgoyal.net/kitty/remote-control/?highlight=dynamic_background_opacity#kitty-set-background-opacity
# kitty @ set-background-opacity $1
# opacity = 0.5