#!/usr/bin/env bash

REPOSITORY="${PWD##*/}"
ROOTDIR=$(echo "${PWD%/*}" | perl -pe 's/^.*\/(\s)*//')

go mod init github.com/$ROOTDIR/$REPOSITORY
echo "go mod init github.com/$ROOTDIR/$REPOSITORY"

example_readme >README.md
example_lc_apache >LICENSE
example_gitignore >.gitignore

perl -i -pe "s/%ROOTDIR/$ROOTDIR/g" LICENSE
perl -i -pe "s/%ROOTDIR/$ROOTDIR/g" README.md
perl -i -pe "s/%REPOSITORY/$REPOSITORY/g" README.md

mkdir cmd && touch cmd/main.go
example_go >cmd/main.go
mkdir pkg
touch .env.example && touch .env

git init && git add .
