#!/usr/bin/env bash

REPOSITORY="${PWD##*/}"
ROOTDIR=$(echo "${PWD%/*}" | perl -pe 's/^.*\/(\s)*//')
SOLCvers=$(solc --version | awk '/Version:/ {print $2}' | cut -d+ -f1)

rm .DS_Store
forge init --force --no-git --no-commit .

example_readme >README.md
example_lc_agpl >LICENSE
example_makefile_forge >Makefile
example_gitignore >.gitignore
example_env >.env.example
example_foundry >foundry.toml

perl -i -pe "s/%ROOTDIR/$ROOTDIR/g" LICENSE
perl -i -pe "s/%ROOTDIR/$ROOTDIR/g" README.md
perl -i -pe "s/%REPOSITORY/$REPOSITORY/g" README.md
perl -i -pe "s/%solcVers/$SOLCvers/g" foundry.toml
find . -type f -name "*.sol" -exec perl -i -pe 's/\/\/ SPDX-License-Identifier: UNLICENSED/\/\/ SPDX-License-Identifier: AGPL-3.0-only/g' {} +
find . -type f -name "*.sol" -exec perl -i -pe "s/pragma solidity \^\\d+\\.\\d+\\.\\d+/pragma solidity ^$SOLCvers/g" {} +

echo "# Auto detect text files and perform LF normalization
* text=auto
.gas-snapshot linguist-language=Julia
*.sol linguist-language=Solidity" >.gitattributes

declare -a dirs=("test" "script")
for dir in "${dirs[@]}"; do
    mkdir -p "$dir/forge"
    mv -iv "$dir/Counter".*.sol "$dir/forge/"
done

mkdir -p ".github/workflows"
example_ghw_sol >.github/workflows/test.yml

git init

echo '[submodule "lib/forge-std"]
	path = lib/forge-std
	url = https://github.com/foundry-rs/forge-std.git' >.gitmodules

libs=(transmissions11/solmate Sol-DAO/solbase OpenZeppelin/openzeppelin-contracts)
selected=()
while true; do
    read -r -p "$(echo -e "\n\033[96m Do you want to install some libraries? [y/\033[1m\033[1;96mn\033[0m\033[96m]\033[0m: ")" response
    if [[ "$response" =~ ^(yes|y)$ ]]; then
        echo -e "\n\033[96m Choices can be space separate\033[0m"
        select lib in "${libs[@]}"; do
            for choice in $REPLY; do
                selected+=(${libs[choice - 1]})
            done
            [[ $selected ]] && break 2
        done
    else
        break
    fi
done

for lib in "${selected[@]}"; do
    echo "Installing $lib ..."
    forge install "$lib" --no-commit
done

forge remappings >remappings.txt
make fmt
git add . && git commit -m "init"
