#!/bin/sh
# cut after =
# y="$1"
# ybe="https://youtu.be/${y##*=}"

youtube-dl --ignore-errors --geo-bypass --add-metadata -x --audio-format mp3 --audio-quality 256K --metadata-from-title "%(artist)s - %(title)s" --exec "mv {} $HOME/Music/" -i "$1"
