---
- name: APT | update && upgrade
  apt:
    update_cache: yes
    upgrade: dist

- name: Reboot if necessary
  stat:
    path: /var/run/reboot-required
  register: result
  changed_when: result.stat.exists
  notify: 'restart server'

- name: Verify new update
  command: uname -mrs
  register: uname_result
      
- name: Display new kernel version
  debug:
    var: uname_result.stdout_lines

- name: APT | remove unused dependency packages
  apt:
    autoremove: yes
    purge: yes