#!/bin/sh

if ! which npm; then
  echo "Doesn't look like Node/NPM are installed."
  echo "Be sure to install them safely with install-node."
  exit 1
fi
npm install -g vercel serverless json2graphql emoji-finder emoj diagnostic-languageserver eslint_d ethers-cli prettier typescript typescript-language-server yarn
