#!/bin/sh

if ! which npm; then
  echo "Doesn't look like Node/NPM are installed."
  echo "Be sure to install them safely with install-node."
  exit 1
fi
npm install -g vercel serverless browser-sync json2graphql csv2geojson osmtogeojson @mapbox/togeojson @mapbox/geojson-merge emoji-finder emoj
