#!/bin/sh

if ! which vim; then
  echo "Doesn't look like vim is installed."
  echo "Be sure to install it safely."
  exit 1
fi

# install coc-json & coc-html and exit
vim -c 'CocInstall -sync coc-vimlsp coc-sql coc-json coc-yaml coc-snippets coc-prettier coc-eslint coc-tsserver coc-explorer coc-sh coc-python|q'
