---
- name: "USER | {{ dotfiles }}"
  git:
    repo: https://github.com/rrobrms/dotfiles
    dest: "{{ item.dir }}/{{ dotfiles }}"
    version: master
  become: yes
  become_user: "{{ item.user }}"
  with_items:
    - { user: "{{ user_sudo }}", dir: "{{ user_sudo_hdir }}/{{ rgh }}/{{ user_sudo }}" }

- name: Remove file
  ansible.builtin.file:
    path: "{{ user_sudo_hdir }}/{{ item.path }}"
    state: absent
  loop:
    - { path: "{{ user_sudo_hdir }}/.bashrc" }
    - { path: "{{ user_sudo_hdir }}/.profile" }

- name: Create Sys links
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: '{{ item.dest }}'
    owner: "{{ item.owner }}"
    group: "{{ item.owner }}"
    force: yes
    state: link
  loop:
    - { src: "{{ user_sudo_hdir }}/{{ rgh }}/{{ user_sudo }}/{{ dotfiles }}/.bashrc", dest: "{{ user_sudo_hdir }}/.bashrc", owner: "{{ user_sudo }}" }
    - { src: "{{ user_sudo_hdir }}/{{ rgh }}/{{ user_sudo }}/{{ dotfiles }}/.profile", dest: "{{ user_sudo_hdir }}/.profile", owner: "{{ user_sudo }}" }
    - { src: "{{ user_sudo_hdir }}/{{ rgh }}/{{ user_sudo }}/{{ dotfiles }}/.inputrc", dest: "{{ user_sudo_hdir }}/.inputrc", owner: "{{ user_sudo }}" }
    - { src: "{{ user_sudo_hdir }}/{{ rgh }}/{{ user_sudo }}/{{ dotfiles }}/.dircolors", dest: "{{ user_sudo_hdir }}/.dircolors", owner: "{{ user_sudo }}" }

- name: Make Scripts files chmod x
  ansible.builtin.file:
    path: "{{ user_sudo_hdir }}/{{ rgh }}/{{ user_sudo }}/{{ dotfiles }}/scripts"
    # mode: u=rwX,g=rX,o=rX
    mode: '0775'
    recurse: yes